### PR TITLE
Changes to getopt and added option to prompt for password

### LINKED ISSUE #16: Password Displayed in Process List (security concern)
I noticed that fvdemount will display the partition's password in the process list (which can be seen by any user), as it is taken as a parameter when mounting. Can this security issue be corrected in a future release?

### PR DESCRIPTION
**Pull request by Rob--W**
I have added two new options, `-P` and `-R` to prompt for the password and recovery password, respectively. The ability to specify a password without explicitly passing it through the command-line arguments fixes #16 and [Debian bug 867110](https://bugs.debian.org/867110).

Before adding the feature, I fixed a few bugs, including major issues such undefined memory deallocation behavior on Windows and infinite loops in argument parsing.

I suggest to review each commit in isolation (and read their commit messages to understand the context of each commit).

### CODE REVIEW

**Comment by joachimmetz** [comment]
Rob thx, I have a look to integrate them as soon as time permits. Regarding the `-P` and `-R`  do you know if they are portable to Windows?

**Comment by Rob--W** [comment]
> Rob thx, I have a look to integrate them as soon as time permits. Regarding the `-P` and `-R` do you know if they are portable to Windows?

I tested on Windows (cross-compiled with MinGW-w64) and the behavior was identical to Linux (with the library-provided `getopt`). I haven't tested with MSVC, but I don't expect any issues since your project already uses parameterless options (e.g. `-h`, `-v`, `-V`).

(At first I tried to do something special upon detecting an empty string parameter. This works as expected on Linux, but not on Windows. So I used `-P` instead of `-p ""`, which in retrospect looks better too.)

I explicitly accounted for the possibility of not having a password, having empty password and having non-empty passwords. Although I don't do any special input processing, passwords with multi-byte UTF-8 should work too because I don't touch bytes with the high order bit set.

**Comment by joachimmetz** [comment]
Heap free issue will be corrected by changes in: https://github.com/libyal/libyal/issues/49

**Comment by Rob--W** [comment]
@joachimmetz Do I need to rebase and remove the commit that fixed the `HeapFree` issue?

**Comment by joachimmetz** [comment]
keep the PR as is. I'll merge or integrate changes step by step, the getopt changes also need to go into libyal

**Comment by joachimmetz** [comment]
small update, I'll try to continue merging these changes shortly

**Comment by joachimmetz** [comment]
confirmed the infinite loop in the fallback getopt implementation, however the proposed changes do not match the getopt behavior. I'll make some adjustments before merge.

**Comment by joachimmetz** [comment]
Password related changes integrated in https://github.com/libyal/libfvde/commit/86e0c5bbbf81a9a9c746744b3fb6dbab700fca03. Note that it was solved differently then proposed. This should cover the proposed functionality. Closing issue.

**Pull request closed without merging**
