### PR TITLE
Renaming README to README.md so that GitHub will render as markdown.

### PR DESCRIPTION
**Pull request by jonathancross**
Also updating a bit of formatting and some links.

### CODE REVIEW

**Comment by joachimmetz** [comment]
Thanks for the proposed changes but, README should remain plain text, since is it distributed.

**Comment by jonathancross** [comment]
Would you be open to just adding the `.md` file extension if no changes were made inside the file? File contents are already compatable with markdown, so it would be much more redable online.

**Comment by joachimmetz** [comment]
>  File contents are already compatable with markdown, so it would be much more redable online.

1. "File contents are already compatable with markdown" please don't mix "markdown as a language" with "markdown as formatter". The file content is plain text, the fact that the markdown formatter is able to recognize URLs is a side effect.
2. If you mean by "redable", nicer formatted then version of README it can be found here: https://github.com/libyal/libfvde/wiki (as IMO expected part of the project documentation)

> Would you be open to just adding the .md file extension if no changes were made inside the file?

No, since adding .md does make sense for distribution, nor does making a copy in README.md. This is something that the github interface could provide for in a more flexible way. It now is forcing a workflow on a project developer/maintainer that does not make sense for this project.

**Comment by jonathancross** [comment]
> the fact that the markdown formatter is able to recognize URLs is a side effect...

I was referring to bulleted lists and reflowing of paragraph text.

But no problem, I can clearly see you are not interested in this change. :-)

Thanks for maintaining this project!

**Pull request closed without merging**
